# Generated by Django 4.2.4 on 2023-09-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adress'),
        ),
    ]
