# Generated by Django 4.2.4 on 2023-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_order_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
